name: Node.js Package

on:
  # release:
  #   types: [created]
  push:
    branches: ["main"]
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: actions/setup-node@v3

  #       with:
  #         node-version: 18
  #     - run: yarn install --imutable
  #     - run: yarn test

  publish-gpr:
    environment:
      name: production
    # needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --imutable
      - run: yarn run build
      - run: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && npm publish --access=public
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}